### ISSUE TITLE
Change project name from SatHelperApp to sat-helper-app

### ISSUE THREAD

**Issue by Gonzih** [opensatelliteproject/SatHelperApp#6]
Hey there, great project!

I noticed couple of naming issues in your project though. 
Main problem is repo issue itself. In Go all import paths are URIs, so they are case insensitive by design, i would highly suggest to rename project in to something like `sat-helper-app` or something similar, otherwise most of go related tooling will struggle to work or will have some issues.

Do you have any thoughts on this? Did you already experience any issues related to this? 

Cheers!

**Comment by Gonzih** [comment]
I thought about it a bit more, and it might just work. I noticed build issues on my side due to camel case in org name, but this is mostly because your org is lower case in github. So disregard this issue for now I suppose :)

**Comment by racerxdl** [comment]
Well the org is upper case: https://github.com/OpenSatelliteProject 
But github alias the lower case as well. And go clones only lower case xD
